name: 'Deploy GitHub Pages site'
description: 'A GitHub Action to deploy an artifact as a GitHub Pages site'

branding:
  icon:
  color:

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  timeout: {}
  error_count: {}
  reporting_interval: {}
  artifact_name:
    description: 'Name of the artifact to deploy'
    required: false
    default: 'github-pages'
  preview:
    description: 'Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)'
    required: false
    default: ${{ !(github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master')) }}

outputs:
  page_url:
    value: ${{ steps.main.outputs.page_url }}
    description: 'URL to deployed GitHub Pages'

runs:
  using: composite
  steps:
    - uses: actions4gh/download-pages-artifact@main
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ runner.temp }}/pagesdata
    - id: main
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
      env:
        PAGESDATA: ${{ runner.temp }}/pagesdata
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PREVIEW: ${{ inputs.preview }}
    
